(dabeaz) yann.yu@mllxv-yu:own_the_dot_with_descriptors$ python -i validate.py 
>>> p = Point(2, 3)
>>> p
<__main__.Point object at 0x7f63447c6da0>
>>> p.x
2
>>> p.y
3
>>> p.x = 45
>>> p.y = 23
>>> p
<__main__.Point object at 0x7f63447c6da0>
>>> p.__dict__
{'x': 45, 'y': 23}
>>> 

>>> p.x = 'a lot'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "validate.py", line 12, in __set__
    raise TypeError('Expected int...')
TypeError: Expected int...
>>> 

